function debugTrialInfo(Sc, cfg)
%% Writes trial info to the top-left of the screen for debugging purposes
%
% Sc - screen object
% cfg - configuration object
%
oldTextSize = Screen('TextSize',Sc.window);
Screen('TextSize',Sc.window,cfg.instr.textSize.small);

t = cfg.currentTrial;

str = ['Trial Number: ' int2str(cfg.currentTrialNumber) '/' int2str(cfg.ntrialsall) '\n' ...
    'Trial ID:' int2str(t.id) '\n' ...
    'Block: ' int2str(t.block) '\n' ...
    ];
if ~isempty(t.choice)
    str = [str ...
        'ChoiceL: ' int2str(t.choice(1)) '\n' ...
        'ChoiceR: ' int2str(t.choice(2)) '\n' ...
        ];
end
str = [str ...
    'AdvisorID: ' int2str(t.advisorID) '\n' ...
    ];
if ~isnan(t.advisorID)
    str = [str ...
        'Advisor: ' cfg.advisor(t.advisorID).name '\n' ...
        'Advice Type: ' int2str(cfg.advisor(t.advisorID).adviceType) '\n' ...
        'Good Advice?: ' int2str(t.obsacc) '\n' ...
        ];
end
str = [str ...
    '\n' ...
    'Answer1: ' int2str(t.wherelarger) '\n' ...
    'Correct?: ' int2str(t.cor) '\n' ...
    ];
%Screen('DrawText',Sc.window,str,0,0,[0 0 0],[1 1 1]);
DrawFormattedText(Sc.window, str, 0, cfg.instr.textSize.small);
Screen('TextSize',Sc.window,oldTextSize);