% overwrite the estimated accuracy question to specify the dot task:
cfg.instr.estimated_obsacc.text = {'On the dot task, your overall accuracy (before any advice) was 71%' ...
    'What do you think this person''s accuracy was on the dot task?' ...
    '[help_string]'...
    'Enter a number between 0 and 100 and press Enter: '};

% Instruction Images
x = [cfg.path.base 'instructions' osSlash 'HaloEffect' osSlash 'Slide'];
cfg.thankYou = [x '22.TIF'];

%% special instructions 
cfg.specialInstructions.intro1 = {[x '1.TIF'] ...
                                    [x '2.TIF'] ...
                                    [x '3.TIF'] ...
                                    [x '4.TIF'] ...
                                    [x '5.TIF'] ...
                                    [x '6.TIF'] ...
                                    [x '7.TIF'] ...
                                    [x '8.TIF'] ...
                                    };
cfg.specialInstructions.intro3 = {[x '9.TIF']};
cfg.specialInstructions.intro4 = {[x '10.TIF']};
cfg.specialInstructions.intro6 = {[x '11.TIF']};

cfg.specialInstructions.block1 = {[x '12.TIF'] [x '13.TIF']};
cfg.specialInstructions.block2 = {[x '14.TIF'] ...
                                    [x '15.TIF'] ...
                                    [x '16.TIF'] ...
                                    [x '17.TIF'] ...
                                    [x '18.TIF'] ...
                                    };
cfg.specialInstructions.block3 = {[x '19.TIF']};
cfg.specialInstructions.block5 = {[x '20.TIF']};
cfg.specialInstructions.block7 = {[x '21.TIF']};

cfg.instructionBlocks = [1 2 3 5 7];