% overwrite the estimated accuracy question to specify the dot task:
cfg.instr.estimated_obsacc.text = {'On the dot task, your overall accuracy (before any advice) was 71%' ...
    'What do you think this person''s accuracy was on the dot task?' ...
    '[help_string]'...
    'Enter a number between 0 and 100 and press Enter: '};

% Instruction Images
x = [cfg.path.base 'instructions' osSlash 'HaloEffect' osSlash 'Slide'];
cfg.thankYou = [x '22.PNG'];

%% special instructions 
cfg.specialInstructions.intro1 = {[x '1.PNG'] ...
                                    [x '2.PNG'] ...
                                    [x '3.PNG'] ...
                                    [x '4.PNG'] ...
                                    [x '5.PNG'] ...
                                    [x '6.PNG'] ...
                                    [x '7.PNG'] ...
                                    [x '8.PNG'] ...
                                    };
cfg.specialInstructions.intro3 = {[x '9.PNG']};
cfg.specialInstructions.intro4 = {[x '10.PNG']};
cfg.specialInstructions.intro6 = {[x '11.PNG']};

cfg.specialInstructions.block1 = {[x '12.PNG'] [x '13.PNG']};
cfg.specialInstructions.block2 = {[x '14.PNG'] ...
                                    [x '15.PNG'] ...
                                    [x '16.PNG'] ...
                                    [x '17.PNG'] ...
                                    [x '18.PNG'] ...
                                    };
cfg.specialInstructions.block3 = {[x '19.PNG']};
cfg.specialInstructions.block5 = {[x '20.PNG']};
cfg.specialInstructions.block7 = {[x '21.PNG']};

cfg.instructionBlocks = [1 2 3 5 7];